[build]
  command = "cd timesheet-app && npm run build"
  publish = "timesheet-app/build"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"
